# Generated by Django 3.1.5 on 2021-01-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0002_auto_20210105_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='static/i'),
        ),
    ]
