# Generated by Django 3.1.5 on 2021-01-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0003_auto_20210106_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.SlugField(default=True, max_length=100, unique=True),
        ),
    ]
