# Generated by Django 3.1.5 on 2021-01-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0004_auto_20210111_1708'),
        ('photo_app', '0004_image_slug'),
    ]

    operations = [
    ]
