# Generated by Django 3.1.5 on 2021-01-12 17:10

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('user_app', '0002_auto_20210106_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.CharField(default=True, max_length=500),
        ),
        migrations.AddField(
            model_name='myuser',
            name='profile_pyxz',
            field=models.ImageField(blank=True, null=True, upload_to='static/i'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='slug',
            field=models.SlugField(default=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
